// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"bbs-logger-consumer/internal/config"
	"bbs-logger-consumer/internal/interfaces"
	"bbs-logger-consumer/internal/repositories"
	services2 "bbs-logger-consumer/internal/services"
	"bbs-logger-consumer/internal/services/interfaces"
	"bbs-logger-consumer/internal/subscriber"
	"fmt"
	"github.com/elastic/go-elasticsearch/v8"
	"net/http"
)

// Injectors from wire.go:

// InitializeService sets up the dependency injection for Service.
func InitService() (services.Service, error) {
	client, err := provideElasticClient()
	if err != nil {
		return nil, err
	}
	v := provideIndexes()
	repository := provideRepository(client, v)
	service := services2.NewService(repository)
	return service, nil
}

// Initialize Subscriber sets up the dependency injection for Service.
func InitSubscriber() (interfaces.Subscriber, error) {
	service, err := InitService()
	if err != nil {
		return nil, err
	}
	config := provideConfigs()
	subscriber := provideSubscriber(service, config)
	return subscriber, nil
}

// wire.go:

// Provide Elasticsearch client
func provideElasticClient() (*elasticsearch.Client, error) {

	configs := config.LoadConfig()

	cfg := elasticsearch.Config{
		Addresses: []string{fmt.Sprintf("%s:%d", configs.DBHost, configs.DBPort)},
		Transport: &http.Transport{
			MaxIdleConnsPerHost: 10,
		},
	}
	return elasticsearch.NewClient(cfg)
}

// Provide the indexes for logging
func provideIndexes() map[string]string {

	configs := config.LoadConfig()

	return map[string]string{
		"general": configs.GeneralIndex,
		"info":    configs.InfoIndex,
		"warning": configs.WarningIndex,
		"error":   configs.ErrorIndex,
		"debug":   configs.DebugIndex,
	}
}

// Provide the configuration
func provideConfigs() *config.Config {

	return config.LoadConfig()
}

// Provide the repository implementation
func provideRepository(esClient *elasticsearch.Client, indexes map[string]string) interfaces.Repository {
	return repositories.NewElasticRepository(esClient, indexes)
}

// Provide the subscriber implementation
func provideSubscriber(s services.Service, c *config.Config) interfaces.Subscriber {
	return subscriber.NewRedisSubscriber(s, c)
}
